import { Product } from "@/types";

export const products: Product[] = [
  // ── Corporate Hampers ───────────────────────────────────────────────────────
  {
    id: "corp-001",
    slug: "executive-welcome-kit",
    name: "Executive Welcome Kit",
    tagline: "A Grand First Impression",
    description:
      "Make every new team member feel like royalty. This curated executive welcome kit blends premium stationery, artisanal treats, and branded memorabilia into one unforgettable first-day experience.",
    price: 3499,
    comparePrice: 4200,
    category: "corporate",
    images: [
      "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=800",
      "https://images.unsplash.com/photo-1607344645866-009c320b63e0?w=800",
      "https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=800",
    ],
    contents: [
      "Premium leather-bound journal",
      "Artisanal chocolate assortment",
      "Gourmet tea selection (6 varieties)",
      "Scented candle – amber & sandalwood",
      "Custom welcome card (handwritten)",
      "Company-branded mug",
      "Luxury kraft gift box with ribbon",
    ],
    personalizationOptions: [
      { id: "p1", label: "Employee Name", type: "text", required: true },
      { id: "p2", label: "Welcome Message", type: "text", required: false },
      {
        id: "p3",
        label: "Ribbon Color",
        type: "select",
        options: ["Gold", "Purple", "Navy", "Ivory"],
        required: false,
      },
    ],
    deliveryTimeline: "3–5 business days",
    badge: "Best Seller",
    inStock: true,
    rating: 4.9,
    reviewCount: 128,
    weight: "1.8kg",
    tags: ["corporate", "welcome", "joining-kit", "employee"],
  },
  {
    id: "corp-002",
    slug: "leadership-appreciation-gift",
    name: "Leadership Appreciation Gift",
    tagline: "For Those Who Lead With Vision",
    description:
      "Honour the leaders who shape your organisation. A sophisticated curation of premium accessories, fine spirits, and artisan crafts — packaged in our signature luxury box.",
    price: 7999,
    comparePrice: 9500,
    category: "executive",
    images: [
      "https://images.unsplash.com/photo-1513885535751-8b9238bd345a?w=800",
      "https://images.unsplash.com/photo-1612387290123-e1e7dcab2a0e?w=800",
    ],
    contents: [
      "Single malt whisky miniature set",
      "Aged Belgian chocolate box (500g)",
      "Hand-crafted leather card holder",
      "Premium fountain pen",
      "Artisan coffee beans (250g)",
      "Crystal desk sculpture",
      "Bespoke luxury box with magnetic closure",
    ],
    personalizationOptions: [
      { id: "p1", label: "Recipient Name", type: "text", required: true },
      { id: "p2", label: "Engraved Message (pen/card holder)", type: "text", required: false },
    ],
    deliveryTimeline: "5–7 business days",
    badge: "Premium",
    inStock: true,
    rating: 5.0,
    reviewCount: 64,
    tags: ["executive", "leadership", "appreciation", "corporate"],
  },
  {
    id: "corp-003",
    slug: "festival-corporate-hamper",
    name: "Diwali Celebrations Hamper",
    tagline: "Light Up Every Relationship",
    description:
      "The ultimate Diwali gifting experience for your clients and employees. A dazzling assortment of sweets, dry fruits, artisan diyas, and premium packaging that announces your brand with elegance.",
    price: 2499,
    category: "festival",
    images: [
      "https://images.unsplash.com/photo-1574158622682-e40e69881006?w=800",
      "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=800",
    ],
    contents: [
      "Assorted premium mithai box (500g)",
      "Mixed dry fruits & nuts (300g)",
      "Artisan hand-painted diyas (set of 5)",
      "Luxury kaju barfi (250g)",
      "Saffron & rose petal tea",
      "Gold-foil gift wrapping",
    ],
    personalizationOptions: [
      { id: "p1", label: "Brand / Company Name (on box)", type: "text", required: false },
      { id: "p2", label: "Festive Message", type: "text", required: false },
    ],
    deliveryTimeline: "3–5 business days",
    badge: "Festival Special",
    inStock: true,
    rating: 4.8,
    reviewCount: 215,
    tags: ["diwali", "festival", "corporate", "sweets"],
  },

  // ── Healthcare Hampers ──────────────────────────────────────────────────────
  {
    id: "hc-001",
    slug: "ivf-journey-hamper",
    name: "IVF Journey Hamper",
    tagline: "Strength, Hope & Love",
    description:
      "A tender, thoughtfully curated hamper for couples embarking on the IVF journey. Filled with calming essentials, nourishing treats, and an uplifting personal message — a warm embrace in a box.",
    price: 3999,
    category: "healthcare",
    images: [
      "https://images.unsplash.com/photo-1559181567-c3190ca9d5db?w=800",
      "https://images.unsplash.com/photo-1505576399279-565b52d4ac71?w=800",
    ],
    contents: [
      "Calming chamomile & lavender tea (20 bags)",
      "Raw honey & almond spread",
      "Organic dark chocolate (70% cacao)",
      "Aromatherapy candle – jasmine & vanilla",
      "Silk eye mask",
      "Handwritten affirmation cards (set of 10)",
      "Fertility wellness journal",
      "Soft linen pouch bag",
    ],
    personalizationOptions: [
      { id: "p1", label: "Recipient Name", type: "text", required: true },
      { id: "p2", label: "Personal Message", type: "text", required: false },
    ],
    deliveryTimeline: "2–4 business days",
    badge: "Most Loved",
    inStock: true,
    rating: 5.0,
    reviewCount: 89,
    tags: ["ivf", "fertility", "healthcare", "emotional"],
  },
  {
    id: "hc-002",
    slug: "pregnancy-celebration-hamper",
    name: "Pregnancy Celebration Hamper",
    tagline: "Celebrating New Life",
    description:
      "A luxurious gift for the mother-to-be — brimming with wellness essentials, premium skincare, and heartfelt keepsakes that celebrate the miracle of new life.",
    price: 4999,
    category: "healthcare",
    images: [
      "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=800",
      "https://images.unsplash.com/photo-1544027993-37dbfe43562a?w=800",
    ],
    contents: [
      "Organic stretch mark oil (100ml)",
      "Prenatal herbal tea blend",
      "Almond & shea body butter",
      "Pregnancy journal & milestone cards",
      "Soft baby onesie (newborn)",
      "Artisan ginger & lemon cookies",
      "Belly butter (natural ingredients)",
      "Luxury box with satin ribbon",
    ],
    personalizationOptions: [
      { id: "p1", label: "Mother's Name", type: "text", required: true },
      { id: "p2", label: "Due Date (for milestone card)", type: "text", required: false },
      {
        id: "p3",
        label: "Baby's Gender (if known)",
        type: "select",
        options: ["Boy", "Girl", "Surprise!"],
        required: false,
      },
    ],
    deliveryTimeline: "3–5 business days",
    badge: "Top Pick",
    inStock: true,
    rating: 4.9,
    reviewCount: 143,
    tags: ["pregnancy", "maternity", "healthcare", "new-mother"],
  },
  {
    id: "hc-003",
    slug: "new-baby-arrival-hamper",
    name: "Baby Arrival Hamper",
    tagline: "Welcome Little One",
    description:
      "A gorgeous celebration hamper for the arrival of a precious new baby. Soft, organic, and utterly delightful — a gift parents and baby will treasure forever.",
    price: 5499,
    category: "baby",
    images: [
      "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=800",
      "https://images.unsplash.com/photo-1586511925558-a4c6376fe65f?w=800",
    ],
    contents: [
      "Organic muslin swaddle blanket",
      "Bamboo cotton bodysuit (set of 3)",
      "Natural baby oil & lotion",
      "Soft knit toy",
      "Baby milestone cards (12 months)",
      "Premium chocolates for parents",
      "Handwritten new arrival card",
      "Keepsake memory box",
    ],
    personalizationOptions: [
      { id: "p1", label: "Baby's Name", type: "text", required: false },
      { id: "p2", label: "Date of Birth", type: "text", required: false },
      {
        id: "p3",
        label: "Theme",
        type: "select",
        options: ["Classic Ivory", "Baby Blue", "Blush Pink", "Sage Green"],
        required: false,
      },
    ],
    deliveryTimeline: "3–5 business days",
    badge: "Gifted Most",
    inStock: true,
    rating: 5.0,
    reviewCount: 201,
    tags: ["baby", "newborn", "maternity", "healthcare"],
  },

  // ── Luxury Hampers ──────────────────────────────────────────────────────────
  {
    id: "lux-001",
    slug: "gourmet-luxury-hamper",
    name: "Grand Gourmet Hamper",
    tagline: "A Feast for the Senses",
    description:
      "Our grandest gourmet offering. An extraordinary collection of the world's finest edibles — from aged cheeses and artisan crackers to premium spirits and single-origin chocolates.",
    price: 9999,
    comparePrice: 12000,
    category: "gourmet",
    images: [
      "https://images.unsplash.com/photo-1607344645866-009c320b63e0?w=800",
      "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800",
    ],
    contents: [
      "Aged cheddar & brie selection",
      "Artisan sourdough crackers & bread sticks",
      "Single-origin chocolate collection (5 origins)",
      "Premium olive oil & balsamic set",
      "Truffle-infused honey",
      "Exotic nuts & trail mix (500g)",
      "Champagne or sparkling wine",
      "Premium tea & coffee selection",
      "Large wicker hamper basket with silk lining",
    ],
    personalizationOptions: [
      { id: "p1", label: "Gift Tag Message", type: "text", required: false },
      {
        id: "p2",
        label: "Alcohol Preference",
        type: "select",
        options: ["Champagne", "Red Wine", "Sparkling Juice (Non-Alcoholic)"],
        required: true,
      },
    ],
    deliveryTimeline: "4–6 business days",
    badge: "Luxury",
    inStock: true,
    rating: 4.9,
    reviewCount: 76,
    tags: ["gourmet", "luxury", "food", "premium"],
  },
  {
    id: "lux-002",
    slug: "wellness-retreat-hamper",
    name: "Wellness Retreat Hamper",
    tagline: "The Gift of Pure Wellbeing",
    description:
      "Bring the spa home. This indulgent wellness hamper combines premium bath & body products, calming aromatherapy, and mindful self-care essentials in our most elegant presentation.",
    price: 6499,
    category: "wellness",
    images: [
      "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800",
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800",
    ],
    contents: [
      "Himalayan salt bath soak (500g)",
      "Aromatherapy essential oil roll-ons (set of 4)",
      "Luxury face mask set (3 variants)",
      "Rose quartz facial roller",
      "Hand-poured soy candle (amber & oud)",
      "Premium bath oils (jasmine & neroli)",
      "Mindfulness journal",
      "Herbal sleep tea blend",
      "Silk sleep mask",
    ],
    personalizationOptions: [
      { id: "p1", label: "Recipient Name", type: "text", required: false },
      {
        id: "p2",
        label: "Scent Preference",
        type: "select",
        options: ["Floral", "Citrus", "Woody", "Fresh"],
        required: false,
      },
    ],
    deliveryTimeline: "3–5 business days",
    badge: "Spa Collection",
    inStock: true,
    rating: 4.8,
    reviewCount: 112,
    tags: ["wellness", "spa", "self-care", "luxury"],
  },
  {
    id: "lux-003",
    slug: "wedding-celebration-hamper",
    name: "Wedding Celebration Hamper",
    tagline: "For A Love That Deserves The Best",
    description:
      "A magnificent gifting experience for the couple beginning their forever. Exquisite in every detail, this hamper sets the tone for a life of shared indulgence and cherished memories.",
    price: 8999,
    category: "wedding",
    images: [
      "https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=800",
      "https://images.unsplash.com/photo-1513278974582-3e1b4a4fa21e?w=800",
    ],
    contents: [
      "Premium sparkling wine (750ml)",
      "Belgian chocolate truffles (24-piece box)",
      "Couples' personalized photo frame",
      "Luxury his & hers perfume set",
      "Artisan candle duo",
      "Dried flower bouquet keepsake",
      "Monogrammed linen napkins",
      "Exotic tea & coffee duo",
      "Handcrafted wooden keepsake box",
    ],
    personalizationOptions: [
      { id: "p1", label: "Couple Names", type: "text", required: true },
      { id: "p2", label: "Wedding Date", type: "text", required: false },
      { id: "p3", label: "Message Card", type: "text", required: false },
    ],
    deliveryTimeline: "5–7 business days",
    badge: "Wedding Special",
    inStock: true,
    rating: 5.0,
    reviewCount: 94,
    tags: ["wedding", "luxury", "couple", "celebration"],
  },
];

export const getProductBySlug = (slug: string) =>
  products.find((p) => p.slug === slug);

export const getProductsByCategory = (category: string) =>
  products.filter((p) => p.category === category);

export const getFeaturedProducts = () =>
  products.filter((p) => p.badge);
